### PR TITLE
RSpec for testing

### PR DESCRIPTION
**Pull request by toaster**
I put the whitespace removal in a separate commit to keep the logic-commit clean.
The lazy data gathering is needed if I want to run tests on my Mac (what I want badly).
As already told: the `Gemfile.lock` is not version controlled for gems normally.
The `.travis.yml` allows you to run the tests automagically on https://travis-ci.org after you have enabled your repository there for free.

### CODE REVIEW

**Comment by toaster** [comment]
Hi there,

I just wanted to check if there is any progress in reviewing this PR.

Regards

**Comment by toaster** [comment]
ping

**Comment by guss77** [comment]
Sorry again for the long time it took me to review this - there are mitigating circumstances such as a week long out of the country business travel, but this pull request should have been done earlier.

Some general comments:
- I see you've done a lot of white spaces - I don't remember being that horrible with white spaces, so I'm not sure what that is about, but I'll accept them now and reserve the right to be a white space nazi in the future ;-)
- I see you've set up a travis.yml file. I'll see about setting up Travis tests, but I'm more attached to Circle CI these days.
- I'm not really in love with the meminfo parsing change - I accept that doing thing in initialize is the Ruby way, and I'm OK with that, but I prefer the one lines. I've accepted it as it is, but I may revisit this in the future.

**Comment by toaster** [comment]
Thanks for merging.

Regarding the white-spaces: It's just that my editor removes any trailing white space (which is IMO garbage) automagically on write. It does so because I told it to. So, every file I touch may have white-space changes just because of this cleanup.

Regarding CI: I just selected the tool I know. I'm not bound to it, so switch to any other solution as you like.

Regarding the meminfo change: That is not about “the Ruby way”. And as you point on it, maybe `initialize` isn't the best place for it. But do it on load is really bad because I have no chance to stub it for tests on non-Linux machines. So the one alternative I see there is to put it into a class method that is called really lazy on first usage.

**Comment by toaster** [comment]
One thing regarding the CI: TravisCI allows to build public repositories without granting them full write access on all of your repositories. They only have read access to the public repos and are allowed to write repository hooks.
As far as I've seen CircleCI _always_ wants full access to all repos which is a totally no-go for me.

And yes, I'm aware that the root of this evil is at GitHub because they don't offer proper permissions.

**Pull request merged**
